### ISSUE TITLE
Swayblur doesn't work with 'sleep' delay.

### ISSUE THREAD

**Issue by dedguy21** [WillPower3309/swayblur#14]
I'm on Arch Linux I have dual monitors so it takes a sec for oguri to recognize the two. 

I wrote a script combining oguri and swayblur to starts within split seconds from launch.

Oguri works as expected, but I always have to run a manual command to get swayblur working under this condition. 

Otherwise swayblur runs only when I don't put a sleep command in front. But then the wallpaper doesn't get set correctly. So I have to manually run oguri . 

Any thoughts as to why?

**Comment by dedguy21** [comment]
I'm just going to close this, and maybe try to work it into a systemd service.

**Comment by WillPower3309** [comment]
Sorry my apologies for not responding to this sooner, I was on vacation. I am happy to look into it as well, im not sure off of the top of my head what the issue would be

**Comment by dedguy21** [comment]
It's ok.  The issue was trying to start oguri && swayblur on the same command line, which absolutely doesn't work, at least through the bash shell. But the sleep delay command works with swayblur individually. Ended separating it out.
