### ISSUE TITLE
Oguri is now archived

### ISSUE THREAD

**Issue by I60R** [WillPower3309/swayblur#16]
I don't know what it means, but perhaps it's better to find a replacement?

**Comment by WillPower3309** [comment]
Thanks for raising this issue! I was never quite happy with oguri as an external dependency. I'll need some time to think about what to do here as the swaybg won't suit our needs. Maybe we can have this project include its own minimal wallpaper daemom

**Comment by I60R** [comment]
Here's a replacement: https://github.com/Horus645/swww (not my project)

**Comment by WillPower3309** [comment]
I actually came across that just yesterday! Thanks for the link, I'll look into implementing it
